name: Update CLI and Create Release

on:
  push:
    branches:
      - main

jobs:
  update-cli:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'

    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev build-essential

    - name: Install Cython
      run: |
        python -m pip install cython

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    - name: Create Release
      uses: softprops/action-gh-release@v2.2.0
      with:
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
        tag_name: Auto
        name: ${{ github.ref }}

    - name: Upload Release Notes
      run: |
        tag=$(git describe --tags)
        echo "Generating release notes for tag: $tag"
        notes=$(python generate_release_notes.py $tag)
        gh release edit $tag --notes "$notes"
